modLoader = "javafml"
loaderVersion = "[2,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/IAFEnvoy/Jupiter/issues"

[[mods]]
modId = "jupiter"
displayName = "Jupiter"
version = "${version}"
logoFile = "logo.png"
authors = "IAFEnvoy"
description = '''A powerful, auto sync config library.'''

[[dependencies.jupiter]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jupiter]]
modId = "minecraft"
type = "required"
